# 只有登录配置，格式最干净，不容易报错
[credentials]
cookie_key = "random_signature_key_pva_lab"
cookie_name = "pva_lab_cookie"
cookie_expiry_days = 30

[credentials.usernames]
[credentials.usernames.admin]
name = "超级管理员"
email = "admin@lab.com"
password = "$2b$12$3uD5.evKM5j.om2jnStR/.v2ganKmhuhoOHcw20j.2rWfZM/4Ddd."